### ISSUE TITLE
Add project structure

### ISSUE THREAD

**Issue by Us1ngTh3Hub** [Us1ngTh3Hub/online_snake#6]
Add the file structure of the project containing
- src folder with subfolders for client, server and network library and corresponding build tools
- doc folder
- test folder
- readme

**Comment by coderr01** [comment]
@Us1ngTh3Hub i would like to make a contribution

**Comment by Us1ngTh3Hub** [comment]
Issue closed with commit ad518dbd4cd389aa3998b6dfc3480e827b297428
